export const DEMO_TEACHERS = [
  { id: "d1", name: "أحمد محمد السالم",    subject: "الرياضيات",           grade_level: "الصف العاشر",      visits: 3, avg_score: 92, status: "completed" },
  { id: "d2", name: "فاطمة علي الزهراني",  subject: "العلوم",               grade_level: "الصف الثامن",      visits: 1, avg_score: null, status: "draft" },
  { id: "d3", name: "خالد عبدالله العمري", subject: "اللغة العربية",        grade_level: "الصف الثاني عشر", visits: 2, avg_score: 76, status: "completed" },
  { id: "d4", name: "نورة سعد القحطاني",   subject: "اللغة الإنجليزية",    grade_level: "الصف العاشر",      visits: 4, avg_score: 95, status: "completed" },
  { id: "d5", name: "محمد إبراهيم الشمري", subject: "التاريخ",              grade_level: "الصف الحادي عشر", visits: 1, avg_score: null, status: "none" },
  { id: "d6", name: "سلمى عمر البلوي",     subject: "التربية الإسلامية",   grade_level: "الصف التاسع",      visits: 6, avg_score: 90, status: "completed" },
];

export const DEMO_EVALUATIONS = [
  { id: "e1",  teacher_id: "d1", status: "completed", date: "2026-06-15", average_score: 4.6, lesson_topic: "المعادلات التربيعية",
    ai_summary: "أظهر المعلم أحمد مستوىً عالياً من الكفاءة في شرح المعادلات التربيعية، مع ربط ممتاز بالتطبيقات الحياتية وإدارة صفية هادئة واحترافية.",
    ai_strengths: "وضوح الشرح وربط المفاهيم بالحياة اليومية\nإدارة الصف بهدوء ومهنية عالية\nتنوع أساليب التقييم خلال الدرس",
    ai_improvement_areas: "تعزيز مشاركة الطلاب بأسئلة تفكير عليا\nتخصيص وقت أكبر للتلخيص الختامي",
    ai_recommendations: "تطبيق استراتيجية التفكير بصوت عالٍ مع الطلاب\nتخصيص 5 دقائق للتقويم الختامي في كل حصة",
    ai_professional_development_plan: "يُنصح بحضور ورشة عمل في استراتيجيات التقييم البنائي خلال الفصل القادم، مع تطبيق نموذج (فكّر - زاوج - شارك) في الحصص القادمة." },
  { id: "e2",  teacher_id: "d1", status: "completed", date: "2026-05-20", average_score: 4.3, lesson_topic: "الدوال والعلاقات",
    ai_summary: "حصة متوازنة جمعت بين النظرية والتطبيق، مع تفاعل جيد من الطلاب وتسلسل منطقي للمحتوى.",
    ai_strengths: "تسلسل منطقي في عرض المحتوى\nتشجيع الطلاب على المشاركة",
    ai_improvement_areas: "الاهتمام أكثر بالطلاب ضعاف الأداء",
    ai_recommendations: "استخدام ورقة عمل تدريبية في نهاية الحصة",
    ai_professional_development_plan: "متابعة أداء الطلاب الأقل تفاعلاً وتقديم دعم إضافي لهم." },
  { id: "e3",  teacher_id: "d1", status: "completed", date: "2026-04-10", average_score: 4.7, lesson_topic: "التفاضل والتكامل",
    ai_summary: "أداء استثنائي في موضوع صعب. أجاد المعلم تبسيط مفاهيم التفاضل والتكامل بأمثلة بصرية واضحة.",
    ai_strengths: "تبسيط المفاهيم الصعبة بالأمثلة البصرية\nحماس واضح ينعكس على الطلاب",
    ai_improvement_areas: "إتاحة وقت أطول لحل التمارين الصفية",
    ai_recommendations: "استخدام برامج الرسوم البيانية التفاعلية (Desmos)",
    ai_professional_development_plan: "تطوير بنك أسئلة تحديٍّ للطلاب المتميزين في الرياضيات." },
  { id: "e4",  teacher_id: "d2", status: "draft",     date: "2026-06-22", average_score: null, lesson_topic: "الخلية وأجزاؤها",
    ai_summary: null, ai_strengths: null, ai_improvement_areas: null, ai_recommendations: null, ai_professional_development_plan: null },
  { id: "e5",  teacher_id: "d3", status: "completed", date: "2026-06-10", average_score: 3.8, lesson_topic: "أساليب النداء والاستفهام",
    ai_summary: "حصة جيدة في مجملها مع شرح وافٍ لأساليب النداء والاستفهام، غير أن الوقت لم يُستغل بأمثل صورة.",
    ai_strengths: "ثروة لغوية واسعة وأمثلة أدبية متنوعة\nتشجيع الطلاب على التعبير الشفهي",
    ai_improvement_areas: "إدارة الوقت وإنهاء الدرس كاملاً\nتقليل وقت الشرح النظري لصالح التطبيق",
    ai_recommendations: "اعتماد خطة درس مُحكمة بتوقيتات واضحة لكل مرحلة",
    ai_professional_development_plan: "حضور برنامج تدريبي في إدارة الوقت الصفي وتصميم خطة الدرس الفعّالة." },
  { id: "e6",  teacher_id: "d3", status: "completed", date: "2026-05-05", average_score: 3.8, lesson_topic: "البلاغة والبيان",
    ai_summary: "الحصة حققت أهدافها الأساسية، مع ملاحظة الحاجة لمزيد من الأنشطة التطبيقية في البلاغة.",
    ai_strengths: "عمق في المعرفة الأدبية والبلاغية\nاستشهادات شعرية ثرية",
    ai_improvement_areas: "تفعيل أنشطة تحليل النصوص بشكل تشاركي",
    ai_recommendations: "تكليف الطلاب بتحليل نصوص قصيرة في مجموعات",
    ai_professional_development_plan: "تطوير مهارة تصميم أنشطة بلاغية تفاعلية." },
  { id: "e7",  teacher_id: "d4", status: "completed", date: "2026-06-18", average_score: 4.9, lesson_topic: "Reading Comprehension",
    ai_summary: "أداء متميز جداً. أبدعت المعلمة نورة في تصميم أنشطة القراءة الفاهمة وتشجيع الطلاب على التفكير النقدي باللغة الإنجليزية.",
    ai_strengths: "تصميم أنشطة قراءة مبتكرة ومتنوعة\nتشجيع التفكير النقدي باللغة الهدف\nمستوى تفاعل الطلاب استثنائي",
    ai_improvement_areas: "مزيد من الاهتمام بنطق بعض المصطلحات الأكاديمية",
    ai_recommendations: "إدراج استراتيجية SQ3R في تعليم القراءة الفاهمة",
    ai_professional_development_plan: "التحضير لبرنامج تدريب الزملاء في مجال تعليم مهارات القراءة الناقدة." },
  { id: "e8",  teacher_id: "d4", status: "completed", date: "2026-06-01", average_score: 4.8, lesson_topic: "Grammar: Present Perfect",
    ai_summary: "حصة نحوية رائعة مع توظيف ممتاز للسياق والأمثلة الحياتية لتوضيح Present Perfect.",
    ai_strengths: "توظيف السياق الحياتي في تعليم القواعد\nإدارة ممتازة للتدريبات الشفهية والكتابية",
    ai_improvement_areas: "تقديم تغذية راجعة فورية أثناء التدريبات",
    ai_recommendations: "استخدام تطبيقات تفاعلية مثل Quizlet لتعزيز القواعد",
    ai_professional_development_plan: "تطوير مصرف أنشطة رقمية للقواعد النحوية." },
  { id: "e9",  teacher_id: "d4", status: "completed", date: "2026-05-15", average_score: 4.7, lesson_topic: "Writing Skills",
    ai_summary: "حصة مهارية متميزة ركزت على تطوير مهارة الكتابة بأسلوب ممنهج وتدريجي.",
    ai_strengths: "التدرج المنطقي في تعليم مهارة الكتابة\nتقديم نماذج نصية واضحة",
    ai_improvement_areas: "إعطاء وقت أطول لمرحلة المراجعة الذاتية",
    ai_recommendations: "اعتماد نموذج كتابة تشاركية (Collaborative Writing)",
    ai_professional_development_plan: "تصميم منهج مكثف لتطوير مهارة الكتابة الإبداعية." },
  { id: "e10", teacher_id: "d4", status: "completed", date: "2026-04-20", average_score: 4.8, lesson_topic: "Vocabulary Building",
    ai_summary: "حصة مفردات غنية بالأنشطة التفاعلية. أظهرت المعلمة إتقاناً في توظيف استراتيجيات تعلم المفردات.",
    ai_strengths: "تنوع استراتيجيات تعلم المفردات\nتوظيف الصور والسياق بفاعلية",
    ai_improvement_areas: "دمج المفردات في نصوص أطول",
    ai_recommendations: "استخدام خرائط المفردات (Vocabulary Maps) في الحصص القادمة",
    ai_professional_development_plan: "بناء قاموس مرئي تراكمي مع الطلاب عبر العام الدراسي." },
  { id: "e11", teacher_id: "d5", status: "completed", date: "2026-06-05", average_score: null, lesson_topic: "الحرب العالمية الأولى",
    ai_summary: null, ai_strengths: null, ai_improvement_areas: null, ai_recommendations: null, ai_professional_development_plan: null },
  { id: "e12", teacher_id: "d6", status: "completed", date: "2026-06-20", average_score: 4.5, lesson_topic: "أركان الإسلام",
    ai_summary: "حصة متوازنة تمزج بين التعليم الديني والقيم الأخلاقية بأسلوب سلس ومؤثر يناسب المرحلة العمرية للطلاب.",
    ai_strengths: "ربط المحتوى الديني بالحياة اليومية للطلاب\nأسلوب تقديم مؤثر ومحفز على الالتزام",
    ai_improvement_areas: "استخدام المزيد من الأنشطة التفاعلية والقصصية",
    ai_recommendations: "إدراج قصص تربوية واقعية في بداية كل حصة",
    ai_professional_development_plan: "تطوير وحدة دراسية قائمة على التعلم بالقصة." },
  { id: "e13", teacher_id: "d6", status: "completed", date: "2026-05-10", average_score: 4.7, lesson_topic: "السيرة النبوية",
    ai_summary: "حصة استثنائية في السيرة النبوية، أبدعت المعلمة في تقديم الأحداث التاريخية بأسلوب قصصي شيّق.",
    ai_strengths: "أسلوب قصصي شيّق يجذب انتباه الطلاب\nعمق في المعلومات وربطها بالسياق",
    ai_improvement_areas: "إضافة خرائط ذهنية لتنظيم الأحداث الزمنية",
    ai_recommendations: "استخدام الخط الزمني البصري لأحداث السيرة",
    ai_professional_development_plan: "تصميم مشروع (موسوعة السيرة) للطلاب على مدار الفصل." },
  { id: "e14", teacher_id: "d6", status: "completed", date: "2026-04-15", average_score: 4.4, lesson_topic: "الفقه الإسلامي",
    ai_summary: "حصة فقهية منظمة تجمع بين الدليل الشرعي والتطبيق العملي، مع توضيح دقيق للمصطلحات.",
    ai_strengths: "دقة في تقديم الأدلة الشرعية\nتطبيق عملي واضح للمسائل الفقهية",
    ai_improvement_areas: "مناقشة آراء الفقهاء بشكل تشاركي أكثر",
    ai_recommendations: "تطبيق نشاط (حالة دراسية فقهية) يناقشها الطلاب في مجموعات",
    ai_professional_development_plan: "حضور دورة في تعليم الفقه بالأنشطة التشاركية." },
  { id: "e15", teacher_id: "d6", status: "completed", date: "2026-03-10", average_score: 4.6, lesson_topic: "التفسير القرآني",
    ai_summary: "حصة تفسيرية رائعة ربطت معاني الآيات بالواقع المعاش بأسلوب يقرّب المعنى للطلاب.",
    ai_strengths: "ربط معاني الآيات بالواقع اليومي\nحفظ الطلاب والتحقق من الفهم",
    ai_improvement_areas: "تعزيز مهارة الطلاب في الاستنباط الذاتي",
    ai_recommendations: "تكليف الطلاب باستنباط درس من آية قرآنية كنشاط بيتي",
    ai_professional_development_plan: "بناء منهج تفسير تدريجي يتراكم على مدار السنة." },
  { id: "e16", teacher_id: "d6", status: "completed", date: "2026-02-20", average_score: 4.5, lesson_topic: "الأخلاق والقيم",
    ai_summary: "حصة قيمية أثّرت في الطلاب بشكل إيجابي من خلال النقاشات المفتوحة حول القيم الإسلامية.",
    ai_strengths: "أسلوب حواري يحفز التفكير الأخلاقي\nنماذج حياتية معاصرة مرتبطة بالقيم",
    ai_improvement_areas: "تقييم مدى استيعاب الطلاب للقيم بشكل موضوعي",
    ai_recommendations: "تطبيق أداة تقييم ذاتي للقيم مع الطلاب",
    ai_professional_development_plan: "تصميم مشروع (قيمة الشهر) يطبقها الطلاب ويوثّقونها." },
  { id: "e17", teacher_id: "d6", status: "completed", date: "2026-01-15", average_score: 4.3, lesson_topic: "العقيدة الإسلامية",
    ai_summary: "حصة عقدية راسخة قدمت مفاهيم التوحيد بوضوح ومنهجية مع ربط جيد بالفطرة الإنسانية.",
    ai_strengths: "وضوح في تقديم مفاهيم التوحيد\nربط الفطرة الإنسانية بالعقيدة",
    ai_improvement_areas: "معالجة الشبهات العقدية الشائعة بين الشباب",
    ai_recommendations: "إدراج حوار عقدي مفتوح في نهاية كل وحدة",
    ai_professional_development_plan: "حضور برنامج الحوار العقدي مع الشباب لتطوير مهارة الجدال العلمي." },
];

export const DEMO_TEACHER_PROFILES: Record<string, {
  ai_report: { summary: string; strengths: string[]; improvements: string[]; recommendations: string[]; development_plan: string };
  visits: { id: string; date: string; topic: string; score: number | null; status: string }[];
}> = {
  d1: {
    ai_report: {
      summary: "يُظهر المعلم أحمد محمد السالم مستوىً مرتفعاً من الكفاءة التدريسية يتجلى في وضوح الشرح وتنوع الاستراتيجيات. أثبتت زياراته الثلاث تحسناً تدريجياً ملحوظاً في إدارة الوقت والتفاعل مع الطلاب.",
      strengths: ["وضوح الشرح وربط المفاهيم بالحياة اليومية", "إدارة الصف بهدوء ومهنية عالية", "تنوع الاستراتيجيات التدريسية"],
      improvements: ["تعزيز مشاركة الطلبة التفاعلية", "الاهتمام بالتقويم المستمر خلال الدرس"],
      recommendations: ["تطبيق استراتيجية التعلم التعاوني", "تخصيص 5 دقائق للتقويم الختامي في كل حصة"],
      development_plan: "يُنصح بحضور ورشة عمل في استراتيجيات التقييم البنائي خلال الفصل القادم.",
    },
    visits: [
      { id: "e1", date: "15 يونيو 2026", topic: "المعادلات التربيعية", score: 92, status: "مكتمل" },
      { id: "e2", date: "20 مايو 2026",  topic: "الدوال والعلاقات",    score: 86, status: "مكتمل" },
      { id: "e3", date: "10 أبريل 2026", topic: "التفاضل والتكامل",    score: 94, status: "مكتمل" },
    ],
  },
  d2: {
    ai_report: {
      summary: "المعلمة فاطمة علي الزهراني تمتلك كفاءة جيدة في تقديم مادة العلوم. التقييم الحالي في مرحلة المسودة ولم تكتمل بيانات الزيارة بعد.",
      strengths: ["توظيف التجارب العملية في الشرح", "بيئة صفية داعمة ومحفزة"],
      improvements: ["إتمام التقييم وتوثيق الملاحظات كاملاً"],
      recommendations: ["استكمال تقرير الزيارة وإضافة الملاحظات التفصيلية"],
      development_plan: "استكمال تقرير الزيارة الحالية ثم تحديد أهداف الفصل القادم.",
    },
    visits: [
      { id: "e4", date: "22 يونيو 2026", topic: "الخلية وأجزاؤها", score: null, status: "مسودة" },
    ],
  },
  d3: {
    ai_report: {
      summary: "يتمتع المعلم خالد عبدالله العمري بثروة لغوية واسعة وأسلوب تقديم متميز لمادة اللغة العربية. يُلاحظ أن إدارة الوقت تحتاج إلى مزيد من الانتباه لإنهاء الدروس بالكامل.",
      strengths: ["ثروة لغوية واسعة وأمثلة أدبية متنوعة", "تشجيع الطلاب على التعبير الشفهي", "عمق في المعرفة البلاغية والنحوية"],
      improvements: ["إدارة الوقت وإنهاء الدرس بالكامل", "تقليل وقت الشرح النظري لصالح التطبيق"],
      recommendations: ["اعتماد خطة درس محكمة بتوقيتات واضحة", "استخدام أنشطة جماعية في تحليل النصوص"],
      development_plan: "حضور برنامج تدريبي في إدارة الوقت الصفي وتصميم خطة الدرس الفعّالة خلال إجازة الفصل.",
    },
    visits: [
      { id: "e5", date: "10 يونيو 2026", topic: "أساليب النداء والاستفهام", score: 76, status: "مكتمل" },
      { id: "e6", date: "5 مايو 2026",   topic: "البلاغة والبيان",          score: 76, status: "مكتمل" },
    ],
  },
  d4: {
    ai_report: {
      summary: "المعلمة نورة سعد القحطاني تُمثّل نموذجاً متميزاً في تدريس اللغة الإنجليزية. أظهرت في زياراتها الأربع أداءً استثنائياً في تصميم الأنشطة وتفعيل التفكير النقدي لدى الطلاب.",
      strengths: ["تصميم أنشطة تعليمية مبتكرة ومتنوعة", "تشجيع التفكير النقدي باللغة الهدف", "مستوى تفاعل الطلاب استثنائي", "ربط المحتوى بالسياق الحياتي"],
      improvements: ["مزيد من الاهتمام بنطق بعض المصطلحات الأكاديمية الدقيقة"],
      recommendations: ["إدراج استراتيجية SQ3R في تعليم القراءة الفاهمة", "استخدام تطبيقات تفاعلية مثل Quizlet"],
      development_plan: "التحضير لبرنامج تدريب الزملاء في مجال تعليم مهارات القراءة الناقدة واللغة الإنجليزية للأغراض الأكاديمية.",
    },
    visits: [
      { id: "e7",  date: "18 يونيو 2026",  topic: "Reading Comprehension",  score: 98, status: "مكتمل" },
      { id: "e8",  date: "1 يونيو 2026",   topic: "Grammar: Present Perfect",score: 96, status: "مكتمل" },
      { id: "e9",  date: "15 مايو 2026",   topic: "Writing Skills",          score: 94, status: "مكتمل" },
      { id: "e10", date: "20 أبريل 2026",  topic: "Vocabulary Building",     score: 96, status: "مكتمل" },
    ],
  },
  d5: {
    ai_report: {
      summary: "المعلم محمد إبراهيم الشمري في بداية مسيرته مع المنصة. الزيارة المسجلة لم تكتمل بياناتها التقييمية بعد، وسيتم توليد تقرير الذكاء الاصطناعي عند اكتمال التقييم.",
      strengths: ["معرفة تاريخية واسعة بالأحداث الكبرى", "أسلوب سرد تاريخي جذاب"],
      improvements: ["استكمال تقييم الزيارة الأولى", "ربط الأحداث التاريخية بالحاضر"],
      recommendations: ["البدء بتوثيق ملاحظات الزيارة الأولى بشكل كامل"],
      development_plan: "إتمام التقييم الأول واستخدامه كنقطة انطلاق لوضع خطة تطوير مخصصة.",
    },
    visits: [
      { id: "e11", date: "5 يونيو 2026", topic: "الحرب العالمية الأولى", score: null, status: "مكتمل" },
    ],
  },
  d6: {
    ai_report: {
      summary: "تُعدّ المعلمة سلمى عمر البلوي من أكثر المعلمين التزاماً بالتطوير المستمر في المنصة بست زيارات مسجلة. تتميز بأسلوبها التربوي الذي يجمع بين العلم الديني والتأثير الأخلاقي على الطلاب.",
      strengths: ["ربط المحتوى الديني بالحياة اليومية للطلاب", "أسلوب تقديم مؤثر ومحفز", "التزام عالٍ بالتطوير المهني المستمر", "تنوع أساليب التعليم بين السردي والتفاعلي"],
      improvements: ["تعزيز مهارة الطلاب في الاستنباط الذاتي", "معالجة الشبهات العقدية الشائعة بين الشباب"],
      recommendations: ["تصميم مشروع (قيمة الشهر) يطبقها الطلاب ويوثّقونها", "استخدام الخط الزمني البصري لأحداث السيرة"],
      development_plan: "يُوصى بالترشح لبرنامج المعلم الخبير وتقديم تجربتها للزملاء في ورش عمل مشتركة الفصل القادم.",
    },
    visits: [
      { id: "e12", date: "20 يونيو 2026",  topic: "أركان الإسلام",      score: 90, status: "مكتمل" },
      { id: "e13", date: "10 مايو 2026",   topic: "السيرة النبوية",      score: 94, status: "مكتمل" },
      { id: "e14", date: "15 أبريل 2026",  topic: "الفقه الإسلامي",     score: 88, status: "مكتمل" },
      { id: "e15", date: "10 مارس 2026",   topic: "التفسير القرآني",     score: 92, status: "مكتمل" },
      { id: "e16", date: "20 فبراير 2026", topic: "الأخلاق والقيم",      score: 90, status: "مكتمل" },
      { id: "e17", date: "15 يناير 2026",  topic: "العقيدة الإسلامية",   score: 86, status: "مكتمل" },
    ],
  },
};
